// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_info_vo.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserInfoVo _$UserFromJson(Map<String, dynamic> json) => UserInfoVo(
  userId: json['userId'] as String?,
  userName: json['userName'] as String?,
  userNickname: json['userNickname'] as String?,
  userAge: json['userAge'],
  userGender: json['userGender'] as String?,
  userPhone: json['userPhone'] as String?,
  userEmail: json['userEmail'] as String?,
  userStatus: (json['userStatus'] as num?)?.toInt(),
  userTheme: json['userTheme'] as String?,
  userOrganiId: json['userOrganiId'] as String?,
  userAvatarId: json['userAvatarId'],
  userLastLoginDate: json['userLastLoginDate'],
  userCreateDate: json['userCreateDate'] as String?,
  userCreateUserId: json['userCreateUserId'] as String?,
  userUpdateDate: json['userUpdateDate'] as String?,
  stateDate: json['stateDate'],
  userUpdateUserId: json['userUpdateUserId'] as String?,
  userDisplay: json['userDisplay'] as bool?,
  userJobTitle: json['userJobTitle'] as String?,
  leader: json['leader'] as bool?,
  userRoles: json['userRoles'],
  userOrgani: json['userOrgani'],
  userAvatar: json['userAvatar'],
  userRealName: json['userRealName'] as String?,
  userIdNumber: json['userIdNumber'] as String?,
  userPasswordExpired: json['userPasswordExpired'] as bool?,
  userPasswordExpiredDate: json['userPasswordExpiredDate'],
  userLoginCount: (json['userLoginCount'] as num?)?.toInt(),
  userCustomPassword: json['userCustomPassword'] as bool?,
  sort: (json['sort'] as num?)?.toInt(),
  tenantUid: json['tenantUid'],
  tenant: json['tenant'],
  rank1Organi: json['rank1Organi'],
  parentOrgani: json['parentOrgani'],
  exit: json['exit'] as bool?,
  admin: json['admin'] as bool?,
);

Map<String, dynamic> _$UserToJson(UserInfoVo instance) => <String, dynamic>{
  'userId': instance.userId,
  'userName': instance.userName,
  'userNickname': instance.userNickname,
  'userAge': instance.userAge,
  'userGender': instance.userGender,
  'userPhone': instance.userPhone,
  'userEmail': instance.userEmail,
  'userStatus': instance.userStatus,
  'userTheme': instance.userTheme,
  'userOrganiId': instance.userOrganiId,
  'userAvatarId': instance.userAvatarId,
  'userLastLoginDate': instance.userLastLoginDate,
  'userCreateDate': instance.userCreateDate,
  'userCreateUserId': instance.userCreateUserId,
  'userUpdateDate': instance.userUpdateDate,
  'stateDate': instance.stateDate,
  'userUpdateUserId': instance.userUpdateUserId,
  'userDisplay': instance.userDisplay,
  'userJobTitle': instance.userJobTitle,
  'leader': instance.leader,
  'userRoles': instance.userRoles,
  'userOrgani': instance.userOrgani,
  'userAvatar': instance.userAvatar,
  'userRealName': instance.userRealName,
  'userIdNumber': instance.userIdNumber,
  'userPasswordExpired': instance.userPasswordExpired,
  'userPasswordExpiredDate': instance.userPasswordExpiredDate,
  'userLoginCount': instance.userLoginCount,
  'userCustomPassword': instance.userCustomPassword,
  'sort': instance.sort,
  'tenantUid': instance.tenantUid,
  'tenant': instance.tenant,
  'rank1Organi': instance.rank1Organi,
  'parentOrgani': instance.parentOrgani,
  'exit': instance.exit,
  'admin': instance.admin,
};
